# Section A:Data Structures & Control Structures

### 1.Create a list of 5 integers.Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [12]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

# append()
numbers.append(60)
print("After append:", numbers)

# extend()
numbers.extend([70, 80])
print("After extend:", numbers)

# insert()
numbers.insert(2, 25)
print("After insert:", numbers)

# remove()
numbers.remove(40)
print("After remove:", numbers)

# pop()
popped = numbers.pop()
print("After pop:", numbers, "| Popped element:", popped)

# index()
index_of_25 = numbers.index(25)
print("Index of 25:", index_of_25)

# count()
count_20 = numbers.count(20)
print("Count of 20:", count_20)

# sort()
numbers.sort()
print("After sort:", numbers)

# reverse()
numbers.reverse()
print("After reverse:", numbers)

Original list: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70] | Popped element: 80
Index of 25: 2
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]


### 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [13]:
# Create a tuple
students = ("Alice", "Bob", "Charlie")
print("Original tuple:", students)

# Try to change the second element
try:
    students[1] = "David"
except TypeError as e:
    print("Error:", e)

print("------------------")
print("Explanation:Tuples are immutable,their elements cannot be changed once created.Attempting to modify an element raises a TypeError")

Original tuple: ('Alice', 'Bob', 'Charlie')
Error: 'tuple' object does not support item assignment
------------------
Explanation:Tuples are immutable,their elements cannot be changed once created.Attempting to modify an element raises a TypeError


### 3.Create a set of integers with some duplicate values. Print the set and explain the output.

In [14]:
# Create a set with duplicates
nums = {1, 1, 2, 3, 4, 4, 5,6}
print("Set with duplicates:", nums)
print("---------------")
print("Explanation:\nSets automatically remove duplicates, so the output will only show unique elements.")

Set with duplicates: {1, 2, 3, 4, 5, 6}
---------------
Explanation:
Sets automatically remove duplicates, so the output will only show unique elements.


### 4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [15]:
# Create a dictionary
person = {'name': 'Devara', 'age': 24, 'city': 'khaansaar'}
print("dict:",person)

# Update age and add email
person['age'] = 26
person['email'] = 'SalaarDevaratha59.com'

print("Updated dictionary:", person)

dict: {'name': 'Devara', 'age': 24, 'city': 'khaansaar'}
Updated dictionary: {'name': 'Devara', 'age': 26, 'city': 'khaansaar', 'email': 'SalaarDevaratha59.com'}


### 5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [16]:
# Voting eligibility
age = 17  # change this to test
if age >= 18:
    print("Eligible to vote.")
else:
    print("Not eligible to vote.")

Not eligible to vote.


### 6.Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [17]:
# Grade calculation
marks = 82  #for example
if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'
print("Grade:", grade)

Grade: B


### 7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [18]:
# Checks if number is positive and even
num = -3  #for example
if num > 0:
    if num % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is negative.


## Section B: Numpy

### 8.Create:
-A scalar using np.array(5)
-A 1D array with values 1 to 5
-A 2D array (2x3) with values from 10 to 60 in steps of 10


In [19]:
# Scalar array
import numpy as np
scalar = np.array(5)
print("Scalar array:\n", scalar)
print("Shape:", scalar.shape)

# 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
# or using np.arange(1, 6)
print("\n1D array:\n", array_1d)

# 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("\n2D array (2x3):\n", array_2d)

Scalar array:
 5
Shape: ()

1D array:
 [1 2 3 4 5]

2D array (2x3):
 [[10 20 30]
 [40 50 60]]


### 9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [20]:
# 4x4 array with random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))
print("\n4x4 Random Integer Array:\n", random_array)


4x4 Random Integer Array:
 [[95 42 71 59]
 [39 24 32 58]
 [ 7 92 12 15]
 [89 55 15 27]]


### 10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [21]:
import pandas as pd

# Create a 3x3 NumPy array
array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Convert to DataFrame with column names
df = pd.DataFrame(array_3x3, columns=['A', 'B', 'C'])
print("\nPandas DataFrame:\n", df)


Pandas DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Section C: Exploring Pandas

### 11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [22]:
# Create a small DataFrame manually
data = {
    'Name': ['Daya', 'Simhadri', 'Bheem', 'Tony', 'Abhi', 
             'Raghu', 'Devara', 'Sparrow', 'Jack', 'Kaboo'],
    'Age': [25, 30, 35, 40, 22, 28, 32, 27, 45, 30],
    'City': ['Hyd', 'Tadipatri', 'Thirupathi', 'Vizag', 'Tokyo', 
             'Mumbai', 'Chennai', 'Berlin', 'Brazil', 'Delhi'],
    'Salary': [50000, 55000, np.nan, 60000, 58000, 
               55000, 62000, np.nan, 70000, 55000]
}

df = pd.DataFrame(data)

print("=== Original DataFrame ===")
print(df)

# .info()
print("\n=== DataFrame Info ===")
print(df.info())

# .describe()
print("\n=== Statistical Summary ===")
print(df.describe())

# Select 'Name' and 'City' columns
print("\n=== Selected Columns: Name & City ===")
print(df[['Name', 'City']])

# Drop 'City' column
df_dropped = df.drop(columns=['City'])
print("\n=== DataFrame after Dropping 'City' Column ===")
print(df_dropped)

# Fill missing values in 'Salary' with mean
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print("\n=== DataFrame after Filling Missing 'Salary' Values ===")
print(df)

# Add a duplicate row intentionally for demonstration
df = pd.concat([df, df.iloc[[2]]], ignore_index=True)
print("\n=== DataFrame with Duplicate Row Added ===")
print(df)

# Remove duplicate rows
df_cleaned = df.drop_duplicates()
print("\n=== DataFrame after Removing Duplicates ===")
print(df_cleaned)

=== Original DataFrame ===
       Name  Age        City   Salary
0      Daya   25         Hyd  50000.0
1  Simhadri   30   Tadipatri  55000.0
2     Bheem   35  Thirupathi      NaN
3      Tony   40       Vizag  60000.0
4      Abhi   22       Tokyo  58000.0
5     Raghu   28      Mumbai  55000.0
6    Devara   32     Chennai  62000.0
7   Sparrow   27      Berlin      NaN
8      Jack   45      Brazil  70000.0
9     Kaboo   30       Delhi  55000.0

=== DataFrame Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

=== Statistical Summary ===
             Age        Salary
count  10.000000      8.000000
mean   31.400000  58125.000000
std     6.9633